CREATE DATABASE GAME_DB;
USE DATABASE GAME_DB;
CREATE SCHEMA PUBLIC;
CREATE TABLE GAME_EVENTS (
  EVENT_ID STRING,
  TS TIMESTAMP_NTZ,
  RECEIVED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

  PLAYER_ID STRING,
  SESSION_ID STRING,
  EVENT STRING,

  SCORE NUMBER,
  SPEED FLOAT,
  COINS NUMBER,

  DATA VARIANT
);
SHOW TABLES;

SELECT EVENT_ID, EVENT, RECEIVED_AT
FROM GAME_DB.PUBLIC.GAME_EVENTS
ORDER BY RECEIVED_AT DESC
LIMIT 10;
SELECT EVENT_ID, EVENT, PLAYER_ID, SESSION_ID, SCORE, COINS, TS, RECEIVED_AT
FROM GAME_DB.PUBLIC.GAME_EVENTS
ORDER BY RECEIVED_AT DESC
LIMIT 30;
